//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeleGroupInfo
    {
        public int ID { get; set; }
        public string GHI_CHU { get; set; }
        public bool IS_ACTIVE { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public string NGUOI_TAO { get; set; }
        public string NGUOI_SUA { get; set; }
        public Nullable<int> TRANG_THAI { get; set; }
        public bool XOA { get; set; }
        public Nullable<System.DateTime> NGAY_XOA { get; set; }
        public string SDT { get; set; }
        public string GROUP_ID { get; set; }
        public string ACCESS_HASH { get; set; }
        public string TITLE { get; set; }
        public string USERNAME { get; set; }
        public Nullable<int> PARTICIPANTS_COUNT { get; set; }
    }
}
